---
- hosts: 192.168.1.213
  become: true
  collections:
    - community.zabbix
  tasks:
  - name: Registro de sistema operacional para APT
    shell: lsb_release -cs
    register: SOAPT
  - name: This command will change the working directory to somedir/
    shell: "echo deb http://apt.postgresql.org/pub/repos/apt {{SOAPT.stdout}}-pgdg main > /etc/apt/sources.list.d/pgdg.list"
  - name: Install Repo-Zabbix-APT
    apt:
      deb: https://repo.zabbix.com/zabbix/5.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.4-1+ubuntu18.04_all.deb
      update_cache: True
  - name: Instalando Zabbix-Agent
    apt:
      name: zabbix-agent
      state: present

  - name: Registro de sistema operacional
    shell: lsb_release -si | tr 'A-Z' 'a-z'
    register: SO
  - name: install postgres
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - postgresql-12
      - postgresql-12-server
      - postgresql-12-llvmjit



#echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
#wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
#apt-get update


