---
- hosts: postgresdb
  become: true
  collections:
    - community.zabbix
  tasks:
  - name: Install Repo-Zabbix
    apt:
      deb: https://repo.zabbix.com/zabbix/5.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.4-1+ubuntu18.04_all.deb
  - name: Removendo Zabbix-Agent
    apt:
      name: zabbix-agent
      state: present

  - name: Registro de sistema operacional
    shell: lsb_release -si | tr 'A-Z' 'a-z'
    register: SO
