---
- hosts: postgresdb
  become: true
  collections:
    - community.zabbix

- name: Install Repo-Zabbix
    apt:
      deb: wget https://repo.zabbix.com/zabbix/5.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.4-1+ubuntu18.04_all.deb

- name: install zabbix 5.4
      package:
        name: "{{ item }}"
        state: present
      loop:
        - zabbix-agent